name: Quine recommended repos for Git Things Done
branding:
  icon: check-square
  color: green
description: |
  Sends you open-source repos that you might be interested in contributing to,
  based on your previous GitHub activity
inputs:
  publish-in:
    description: "Tells the action where to publish your repo recommendations. Valid: `separate-issue` and `porter-issue`. Default: `porter-issue`"
    required: false
  run-cron:
    description: "A cron schedule expression that tells the action when to publish your recommended repos."
    required: true
  gh-pat:
    description: "PAT. Used to store Quine API access tokens in your repo's secrets. Scope needed: repo: all and org: read"
    required: true
  quine-access-token:
    description: "Access token used to query Quine's API for you recommended repos."
    required: false
  quine-refresh-token:
    description: "Refresh token that will be exchanged for a Quine access token after the latter expires."
    required: false
runs:
  using: docker
  image: Dockerfile
